package views;

import DAO.ServicoDAO;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.Servico;

/**
 *
 * @author marcu
 */
public class TelaServico extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaServico() {
        initComponents();
        txtDesc.grabFocus();
        setIcon();

    }

    public void readJTable() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tableService.getModel();
        tableService.setRowSorter(new TableRowSorter(modelo));
        modelo.setNumRows(0);

        ServicoDAO servicoDao = new ServicoDAO();

        for (Servico servico : servicoDao.read()) {
            modelo.addRow(new Object[]{
                servico.getId(),
                servico.getDescricao(),
                servico.getValor()

            });
        }

    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtSrch1 = new javax.swing.JTextField();
        btnSrch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnExcd = new javax.swing.JButton();
        btnUpd = new javax.swing.JButton();
        btnCln = new javax.swing.JButton();
        btnExt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableService = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Serviços");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setEditable(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 50, -1));
        jPanel1.add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 410, -1));
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 200, -1));
        jPanel1.add(txtSrch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 280, -1));

        btnSrch.setText("Pesquisar");
        jPanel1.add(btnSrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        btnExcd.setText("Excluir");
        jPanel1.add(btnExcd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 80, -1));

        btnUpd.setText("Atualizar");
        jPanel1.add(btnUpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 80, -1));

        btnCln.setText("Limpar");
        jPanel1.add(btnCln, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 80, -1));

        btnExt.setText("Fechar");
        btnExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtActionPerformed(evt);
            }
        });
        jPanel1.add(btnExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, -1));

        tableService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableService);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 690, 180));

        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel3.setText("Descrição");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel4.setText("Valor");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        lblBg.setMaximumSize(new java.awt.Dimension(800, 500));
        lblBg.setMinimumSize(new java.awt.Dimension(800, 500));
        lblBg.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtActionPerformed
        // TODO add your handling code here:
        TelaServico.this.dispose();
    }//GEN-LAST:event_btnExtActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //
        if (!txtValor.getText().isEmpty() && !txtDesc.getText().isEmpty()) {
            Servico servico = new Servico();
            ServicoDAO dao = new ServicoDAO();
            servico.setDescricao(txtDesc.getText());
            servico.setValor(Float.parseFloat(txtValor.getText()));
            try {
                dao.create(servico);
            } catch (SQLException ex) {
                System.out.println("Erro ao Cadastrar no banco de dados" + ex);
            }
            try {
                readJTable();
            } catch (SQLException ex) {
                System.out.println("Erro ao conectar ao banco" + ex);
            }

            limpar();

        } else {
            JOptionPane.showMessageDialog(null, "Informe a Descrição e o valor do serviço!");
        }

    }//GEN-LAST:event_btnAddActionPerformed
    public void limpar() {
        txtId.setText("");
        txtDesc.setText("");
        txtValor.setText("");
        txtValor.setText("");

        txtDesc.grabFocus();

        btnAdd.setEnabled(true);
        txtValor.setEnabled(true);
        btnSrch.setEnabled(true);

        btnExcd.setEnabled(false);
        btnUpd.setEnabled(false);

        try {
            readJTable();
        } catch (SQLException ex) {
            System.out.println("Erro ao conectar ao banco" + ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaServico().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCln;
    private javax.swing.JButton btnExcd;
    private javax.swing.JButton btnExt;
    private javax.swing.JButton btnSrch;
    private javax.swing.JButton btnUpd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBg;
    private javax.swing.JTable tableService;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtSrch1;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
